### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by kakachiex2** [Sparky4567/obsidian_ai_plugin#2]
I get this error when executing "ai ask llm"
I install directly from obsidian plugins community plugins section in setting
![Screenshot 2024-05-05 121038](https://github.com/Sparky4567/obsidian_ai_plugin/assets/1762112/35d42d53-b537-4ca3-b59d-65b7ef933c83)

**Comment by kakachiex2** [comment]
I have the ollama running in the background

**Comment by Sparky4567** [comment]
Hello Rafael,

Did you run the plugin according to the documentation provided on Github?


2024-05-05, sk 19:20, Rafael Nolasco ***@***.***> rašė:

**Comment by kakachiex2** [comment]
nope I install directly from the obsidian community plugins manager, I try to install manually from git documentation and get errors with npm install process
![Screenshot 2024-05-05 131430](https://github.com/Sparky4567/obsidian_ai_plugin/assets/1762112/05a3de6d-7a0d-40d7-a6d4-372a73bb74d5)

**Comment by Sparky4567** [comment]
Hey @kakachiex2 ,

Could you provide me with an error log from the build process?
