### ISSUE TITLE
Endpoint setting not taken into account

### ISSUE THREAD

**Issue by jggc** [Sparky4567/obsidian_ai_plugin#5]
Thanks for building this very simple plugin!

My custom ollama endpoint is set and saved properly in data.json but I have to override this.Host in the Ollama2 constructor as it does not read from the plugin settings.

**Comment by Sparky4567** [comment]
Hey @jggc , Version 1.1.3 should solve the issue, it lets you to specify a custom IP address from now on. [](https://github.com/Sparky4567/obsidian_ai_plugin/releases/tag/1.1.3)

**Comment by Sparky4567** [comment]
https://github.com/Sparky4567/obsidian_ai_plugin/releases/tag/1.1.3
